server:
  port: 8989       #端口号
  servlet:
    context-path: /springboot      #访问时的项目名
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MyCat端口号  test_schema逻辑库名?拼接characterEncoding=UTF-8编码格式
    #防止jar包运行时出现中文乱码
    url: jdbc:mysql://192.168.44.134:8066/test_schema?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver    #加载驱动
  servlet:
    multipart:
      max-file-size: 500KB     #单个文件   默认1MB
      max-request-size: 5GB    #同时上传多个文件  默认10MB
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: 'yyyy-MM-dd hh:mm:ss'
  profiles:
    active: product
  http:
    encoding:
      charset: UTF-8
      force: true
      force-request: true
      force-response: true
  jackson:
    date-format: 'yyyy-MM-dd hh:mm:ss'
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity
logging:
  level:
    root: info
    com.baizhi.dao: debug
  file: D:/testLog.log  #指定输出的文件夹+文件名
  pattern:
    console: '[%p] %d{yyyy-MM-dd hh:mm:ss} %m %n'
    file: '[%p] %d{yyyy-MM-dd hh:mm:ss} %m'